/*

Copyright (c) 2005-2026, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#ifndef TESTLOOKUPTABLEBACKWARDSCOMPATIBILITY_HPP_
#define TESTLOOKUPTABLEBACKWARDSCOMPATIBILITY_HPP_

#include <cxxtest/TestSuite.h>
#include "CheckpointArchiveTypes.hpp"

#include <fstream>
#include "FileFinder.hpp"
#include "ParameterBox.hpp"

/**
 * Check that lookup table data structures archived by older versions of ApPredict
 * (which refined by subdividing boxes into 2^DIM) still load, interpolate identically,
 * and can be refined further by the current code (which bisects boxes).
 *
 * The archive in test/data/legacy_lookup_tables was generated by
 * test/data/legacy_lookup_tables/GenerateLegacyParameterBoxFixture.cpp with the older code.
 * See also TestConvertLookupTableArchiveToBinary for a check on a published lookup table.
 */
class TestLookupTableBackwardsCompatibility : public CxxTest::TestSuite
{
private:
    /** The function that was used to generate the legacy archive */
    static double Separable2d(const c_vector<double, 2u>& rX)
    {
        return exp(rX[0]) * (1.0 + rX[1] * rX[1]);
    }

    void AssignDataAtPoint(ParameterBox<2>& rBox, c_vector<double, 2u>* pPoint)
    {
        std::vector<double> qoi(1u, Separable2d(*pPoint));
        rBox.AssignQoIValues(pPoint, boost::shared_ptr<ParameterPointData>(new ParameterPointData(qoi, 0u)));
    }

    double MaxInterpolationError(ParameterBox<2>& rBox)
    {
        double max_error = 0.0;
        for (unsigned i = 0; i <= 20u; i++)
        {
            for (unsigned j = 0; j <= 20u; j++)
            {
                c_vector<double, 2u> point;
                point[0] = 0.05 * i;
                point[1] = 0.05 * j;
                max_error = std::max(max_error, fabs(rBox.InterpolateQoIsAt(point)[0] - Separable2d(point)));
            }
        }
        return max_error;
    }

public:
    void TestLoadAndRefineLegacyParameterBox()
    {
        FileFinder archive_file("projects/ApPredict/test/data/legacy_lookup_tables/ParameterBox2d_legacy.arch",
                                RelativeTo::ChasteSourceRoot);
        FileFinder interpolated_file("projects/ApPredict/test/data/legacy_lookup_tables/ParameterBox2d_legacy_interpolated.dat",
                                     RelativeTo::ChasteSourceRoot);
        TS_ASSERT(archive_file.IsFile());
        TS_ASSERT(interpolated_file.IsFile());

        ParameterBox<2>* p_box;
        {
            std::ifstream ifs(archive_file.GetAbsolutePath().c_str(), std::ios::binary);
            boost::archive::text_iarchive input_arch(ifs);
            input_arch >> p_box;
        }

        // Check this is the structure we expect from the old algorithm
        TS_ASSERT_EQUALS(p_box->GetCorners().size(), 153u);
        TS_ASSERT_EQUALS(p_box->GetDaughterBoxes().size(), 4u);

        // Interpolation should be identical to the old code
        std::ifstream interpolated_stream(interpolated_file.GetAbsolutePath().c_str());
        unsigned num_points_checked = 0u;
        double x, y, value;
        while (interpolated_stream >> x >> y >> value)
        {
            c_vector<double, 2u> point;
            point[0] = x;
            point[1] = y;
            TS_ASSERT_DELTA(p_box->InterpolateQoIsAt(point)[0], value, 1e-12);
            num_points_checked++;
        }
        TS_ASSERT_EQUALS(num_points_checked, 441u);

        // The legacy table was refined to this tolerance, and the new code should agree that it is converged.
        const double legacy_tolerance = 5e-2;
        TS_ASSERT(p_box->FindBoxWithLargestQoIErrorEstimate(0u, legacy_tolerance) == NULL);
        TS_ASSERT_DELTA(p_box->ReportPercentageOfSpaceWhereToleranceIsMetForQoI(legacy_tolerance, 0u), 100.0, 1e-9);

        // Carry on refining with bisection, as the LookupTableGenerator would now do.
        const double tolerance = 5e-3;
        unsigned num_bisections = 0u;
        while (ParameterBox<2>* p_refine = p_box->FindBoxWithLargestQoIErrorEstimate(0u, tolerance))
        {
            std::set<c_vector<double, 2u>*, c_vector_compare<2u> > new_points = p_refine->SubDivide(p_refine->ChooseDimensionToSplit(0u));
            TS_ASSERT_LESS_THAN_EQUALS(new_points.size(), 2u);
            TS_ASSERT_EQUALS(p_refine->GetDaughterBoxes().size(), 2u);
            for (auto iter = new_points.begin(); iter != new_points.end(); ++iter)
            {
                AssignDataAtPoint(*p_box, *iter);
            }
            num_bisections++;
            TS_ASSERT_LESS_THAN(num_bisections, 10000u);
            if (num_bisections >= 10000u)
            {
                break;
            }
        }
        TS_ASSERT_LESS_THAN(0u, num_bisections);
        TS_ASSERT_LESS_THAN(153u, p_box->GetCorners().size());
        TS_ASSERT_LESS_THAN(MaxInterpolationError(*p_box), tolerance);

        delete p_box;
    }
};

#endif // TESTLOOKUPTABLEBACKWARDSCOMPATIBILITY_HPP_
