name: Ubuntu 20.04 ApPredict test suite

on:
  push:
    branches:
      - master
      
  schedule:
    - cron:  '0 0 * * *'
    
  workflow_dispatch:
  
jobs:

  build-and-test:

    name: Build and test on Ubuntu 20.04
    runs-on: [self-hosted, ubuntu-20.04]
    env:
      CHASTE_TEST_OUTPUT: ${{ github.workspace }}/chaste-test-dir
      CHASTE_SRC_DIR: ${{ github.workspace }}/Chaste
      CHASTE_BUILD_DIR: ${CHASTE_SRC_DIR}/build
      CC: gcc
      CXX: g++
      
    steps:
    - name: checkout Chaste repository
      uses: actions/checkout@v3
      with:
        repository: Chaste/Chaste
        path: ${CHASTE_SRC_DIR}
        submodules: recursive
      
    - name: checkout ApPredict project
      uses: actions/checkout@v3
      with:
        repository: Chaste/ApPredict
        path: ${CHASTE_SRC_DIR}/projects/ApPredict
        submodules: recursive
        
    - name: ${CXX} version
      run: |
        ${CXX} --version
        ${CXX} --version > compiler.version
        
    - name: cache build directory
      uses: actions/cache@v3
      id: cache
      with:
        path: ${CHASTE_BUILD_DIR}
        key: ${{ runner.os }}-${{ hashFiles('docs/ReleaseNotes.html') }}-${{ hashFiles('compiler.version') }}

    - name: make build and test directories
      run: |
        mkdir -p ${CHASTE_BUILD_DIR}
        mkdir -p ${CHASTE_TEST_OUTPUT}
        
    - name: cmake configure
      run: cmake -DCMAKE_BUILD_TYPE=Release ${CHASTE_SRC_DIR}
      working-directory: ${CHASTE_BUILD_DIR}

    - name: build core libraries
      run: cmake --build . --parallel 8 --target chaste_core
      working-directory: ${CHASTE_BUILD_DIR}

    - name: build heart
      run: cmake --build . --parallel 8 --target chaste_heart
      working-directory: ${CHASTE_BUILD_DIR}
      
    - name: build ApPredict test pack
      run: cmake --build . --parallel 8 --target ApPredict
      working-directory: ${CHASTE_BUILD_DIR}

    - name: run ApPredict test pack
      run: ctest -j8 -L ApPredict --output-on-failure
      working-directory: ${CHASTE_BUILD_DIR}
